[project]
authors = [{ name = "Lorenzo Wormer", email = "l.wormer@mailbox.org" }]
requires-python = ">=3.12"
dynamic = ["version"]
dependencies = [
    "aiohttp>=3.10.8",
    "babel<3.0.0,>=2.12.1",
    "beartype>=0.18.5",
    "beautifulsoup4>=4.12.2",
    "cloudpathlib>=0.18.1",
    "country-converter<2.0,>=1.2",
    "deep-translator<2.0.0,>=1.11.0",
    "fastexcel>=0.12.1",
    "GitPython>=3.1.40",
    "identify>=2.6.12",
    "imgkit<2.0.0,>=1.2.3",
    "importlib-metadata>=6.11.0",
    "ipython>=8.21.0",
    "ipywidgets>=8.1.1",
    "lxml>=5.2.2",
    "networkx>=3.4.2",
    "notebook>=7.0.6",
    "numpy>=2.0.0",
    "openpyxl<4.0.0,>=3.0.9",
    "packaging>=23.2",
    "pandas-stubs>=2.1.4.231227",
    "pandas<4.0,>=3.0.1",
    "pandera>=0.21.1",
    "pdfkit<2.0.0,>=1.0.0",
    "pillow>=11.2.1",
    "plotly<7,>=6.6.0",
    "polars>=1.8.0,<2",
    "pydantic-core>=2.14.6",
    "pydantic<3.0,>=2.5.3",
    "PyYAML<7.0,>=6.0",
    "requests>=2.31.0",
    "rich>=14.3.3",
    "sphinx>=7.2.6",
    "sqlalchemy<3.0.0,>=2.0.7",
    "sqlparse>=0.5.3",
    "strenum<1.0.0,>=0.4.10",
    "structlog<26,>=25.5.0",
    "tenacity>=8.5.0",
    "tqdm<5.0.0,>=4.62.3",
    "types-lxml>=2026.2.16",
    "typing-extensions<5.0.0,>=4.13.0",
    "webcolors<26,>=25.10.0",
    "XlsxWriter>=3.2.0",
    "yarl>=1.9.4",
]
name = "py-research"
description = "Collection of utilities for R&D coding in Python 🐍"
readme = "README.md"

[project.urls]
Documentation = "https://cloudlane-one.github.io/py-research/"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.dev-dependencies]
dev = [
    "black>=24",
    "pytest>=7.4.3",
    "pygments>=2.17.2",
    "nbsphinx>=0.9.3",
    "myst-parser>=2.0.0",
    "pydata-sphinx-theme>=0.14.4",
    "autodoc-pydantic>=1.9.0",
    "deptry>=0.12.0",
    "ruff>=0.1.7",
    "pytest-cov>=4.1.0",
]

[tool.pdm.build]
includes = ["src/py_research"]

[tool.pdm.version]
source = "scm"

[tool.ruff]
# Enable following linters:
# - pycodestyle (`E`, `W`)
# - Pyflakes (`F`)
# - mccabe (`C90`)
# - pep8-naming (`N`)
# - pydocstyle (`D`)
# - pyupgrade (`UP`)
select = ["E", "W", "F", "C90", "N", "D", "UP"]
line-length = 120

[tool.ruff.lint]
ignore = [
    "UP046", # Old-style type-params for classes
    "UP047", # Old-style type-params for functions
    "D105",  # Undocumented magic methods
    "D107",  # Missing docstring in init method
]

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.mccabe]
# Flag errors (`C901`) whenever the complexity level exceeds 5.
max-complexity = 20

[tool.deptry]
known_first_party = ["py_research"]

[tool.deptry.per_rule_ignores]
DEP002 = [
    "openpyxl",
    "pandas-stubs",
    "notebook",
    "ipywidgets",
    "fastexcel",
    "pandera",
]

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
pythonpath = ["src"]

[tool.pyright]
reportMatchNotExhaustive = true
reportIncompatibleVariableOverride = true
reportIncompatibleMethodOverride = true
reportOverlappingOverload = true
