name: Lint & Test

on:
  pull_request:
    branches: [main]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - run: sudo locale-gen en_US
      - run: sudo locale-gen de_DE
      - run: sudo update-locale
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.11
          cache: true
      - run: pdm install
      - run: source .venv/bin/activate
      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH
      - name: Check Black formatting
        run: black src --check
      - name: Check for dependency issues with deptry
        run: deptry ./
      - name: Check for outdated dependencies
        run: python ./scripts/find_outdated_deps.py
      - name: Lint with Ruff
        run: ruff check --output-format=github .
      - name: Typecheck with Pyright
        uses: jakebailey/pyright-action@v1
      - name: Test with pytest
        run: pytest --doctest-modules --cov=./src --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
